INSERT INTO "Books" ("Id", "Title", "Author", "Price", "Image", "Description", "ImageFile") VALUES (1, 'Duna', 'Frank Herbert', '12.99', 'https://mrtns.sk/tovar/_l/312/l312629.jpg?v=17311053612', 'Duna je sci-fi séria románov od amerického spisovateľa Franka Herberta. Knihy zo série Duna sa okrem precízne vytvoreného fiktívneho sveta zaoberajú aj politikou, ekológiou a filozofiou. Ponúkajú čitateľovi predovšetkým jedno: veľký a dobrodružný príbeh.' ||
                                                                                                                                                                                    '

            Aj keď Duna hneď po vydaní získala dve najprestížnejšie ceny v žánri sci-fi, jej popularita rástla až postupne v šesťdesiatych a sedemdesiatych rokoch, predovšetkým vďaka zanieteným fanúšikom.

            Púštna planéta Arrakis je jediným miestom, kde možno nájsť vzácne korenie, ktoré predlžuje ľuďom život a zároveň ich obdarúva výnimočnými psychickými schopnosťami. Na pozadí tohto neľútostného a drsného sveta sa rozohráva komplikovaný boj o moc medzi znepriatelenými veľkorodmi, ktoré by rady náleziská na Arrakise ovládali.', null);
INSERT INTO "Books" ("Id", "Title", "Author", "Price", "Image", "Description", "ImageFile") VALUES (2, 'Metro 2035', 'Dmitry Glukhovsky', '15.99', 'https://mrtns.sk/tovar/_l/224/l224980.jpg?v=17194609142', 'ok 2035. Svetlá minulosť. Temná budúcnosť. Jadrová vojna zničila civilizáciu na Zemi v podobe, ako ju poznáme dnes. Prežilo iba niekoľko desiatok tisíc ľudí, ktorí sa utiahli do moskovského metra, aby sa zachránili pred rádioaktívnym žiarením na povrchu. Napriek vyhubeniu podstatnej časti ľudstva sa obyvatelia metra nedokázali zjednotiť a okrem túžby prežiť si priniesli aj bremeno zastaraných ideológií. Podzemný svet sa tak podľa vzoru bývalej civilizácie rozdelil na akési novodobé štáty. Ekonomickým centrom metra je Hanza, známa svojím obchodníckym duchom. Intelektuáli si našli miesto v Polise. Nechýbajú ani komunisti zjednotení v Červenej linke a fašisti zoskupení v Ríši. Odveké nepriateľstvo dvoch hlavných ideológií privedie metro na pokraj občianskej vojny a ľudstvu hrozí zánik. Ale sú naozaj jediní, kto prežil apokalypsu? Mladý záchranca metra Arťom sa nemôže zmieriť s faktom, že nikde inde na svete už nežijú ľudia. Pokračuje vo výpravách na povrch a pokúša sa zachytiť signál z akéhokoľvek kúta zemegule. Pomaly stráca nádej, keď do jeho neúspešného hľadania zasiahne náhoda. Od starého spisovateľa Homéra sa dozvie o cudzincoch, ktorí vraj z povrchu prišli do metra. Arťomovi viac netreba a vydáva sa na cestu naprieč metrom, aby zistil, či sú správy o prišelcoch zvonku pravdivé. Počas putovania odhalí sprisahanie, ktoré otrasie základmi jeho presvedčenia, a zistí, že aj svet metra má svoje sivé eminencie manipulujúce životmi bežných ľudí.', null);
INSERT INTO "Books" ("Id", "Title", "Author", "Price", "Image", "Description", "ImageFile") VALUES (3, 'Zaklínač', 'Andrzej Sapkowski', '9.99', 'https://mrtns.sk/tovar/_xl/2467/xl2467597.jpg?v=17331461882', 'aklínač je literárny fantasy cyklus poľského spisovateľa Andrzeja Sapkowského. Základom cyklu je literárna predloha, ktorú tvorí niekoľko poviedkových kníh a románová séria. Hlavnou postavou cyklu je zaklínač Geralt z Rivie. Ten sa živí ako nájomný zabijak mýtických príšer a netvorov v realisticky vykreslenom svete, kde sa ako netvori správajú často aj obyčajní ľudia. Zaklínač pôvodne vychádzal ako séria poviedok v časopise Fantastyka. Sapkowski neskôr poviedky vydal knižne a v 90. rokoch napísal aj 5-zväzkovú románovú ságu. V roku 2001 sa predloha dočkala aj poľskej seriálovej adaptácie. Fantazijný cyklus globálne preslávila až séria počítačových hier na motívy kníh Zaklínač (2007, 2011 a 2015) z dielne poľského štúdia CD Projekt RED, čo viedlo tiež k anglickému (2008) a slovenskému (2015) prekladu kníh, a napokon k seriálovej adaptácii predlohy od štúdia Netflix z roku 2019, Zaklínač.', null);
INSERT INTO "Books" ("Id", "Title", "Author", "Price", "Image", "Description", "ImageFile") VALUES (4, 'Hyperion', 'Dan Simmons', '18.9', 'https://mrtns.sk/tovar/_xl/2475/xl2475299.jpg?v=17332022052', 'Kultová vesmírna opera, jedna z najdôležitejších sci-fi ság histórie. Na planéte Hyperion, za hranicami vplyvu zákonov Hegemónie človeka, číha hrozivý tvor menom Rapír. Niektorí ho uctievajú, iní sa ho desia a ďalší ho chcú zničiť. Rapír vyčkáva v Údolí Hrobiek času, kde sa zlovestné monumenty hýbu proti prúdu času. V predvečer armagedonu sa sedem pútnikov vydáva na poslednú cestu na Hyperion hľadať odpovede na nevyriešené hádanky vlastných životov. Každý z nich si nesie zúfalú nádej a strašné tajomstvo. A jeden z nich môže mať v rukách osud celého ľudstva.', null);
INSERT INTO "Books" ("Id", "Title", "Author", "Price", "Image", "Description", "ImageFile") VALUES (6, ' Malý princ ', 'Antoine de Saint-Exupéry', '10.56', 'https://mrtns.sk/tovar/_xl/656/xl656055.jpg?v=17386453922', '„Nakresli mi barančeka.“ Touto prosbou osloví malý chlapec so zlatistými kučerami pilota, ktorý havaroval v saharskej púšti. Odkiaľ sa tam to chlapča vzalo? Priletelo azda z nejakej vzdialenej planéty v spoločnosti sťahovavých vtákov? Alebo je to svojím spôsobom prízrakové dieťa len výplodom pilotovej fantázie?

Ikonickú novelu Malý princ prinášame v novom preklade Igora Navrátila a grafickom spracovaní vychádzajúcom z prvého amerického vydania knihy, na ktorom pracoval samotný Antoine de Saint-Exupéry.

Rozsahom síce útle, ale humánnym posolstvom rozsiahle dielo možno čítať ako rozprávku či alegóriu alebo symbolický existenciálny román.', null);
